### PR TITLE
65 uml added visuals for better understanding

### PR DESCRIPTION
**Pull request by evanvang**
fixes issue #33

### CODE REVIEW

**Comment by evanvang** [comment]
converted images to markdown syntax

**Comment by evanvang** [comment]
All checks have passed

**Comment by onzfonz** [comment]
yeah, so I don't think you did these...did you?  We want to cite our sources here.
Also, you can for example try to create a simple uml diagram using plantuml.

If you did not complete this lab, then I would have you either:
1. try to complete the lab first, then see what hiccups there are
2. work on something else.

Feel free to message me tomorrow and we can consider something else

**Comment by onzfonz** [comment]
This was never finished here.

**Comment by evanvang** [comment]
hey professor, I was never able to finish it because when I tried to go
back this was a day after it had already closed for me so I couldn't do
anything. Is there any way you could open it back up for me?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
