### PR TITLE
Fix 13-Refact code blocks

### PR DESCRIPTION
**Pull request by DeanShin**
Fixes: #5

### CODE REVIEW

**Review by onzfonz — CHANGES_REQUESTED** [review]
Can you change line 248 to perhaps a single quoted backtick as well, and potentially not on it's own line?
Seems to also not be rendering correctly based on it being on it's own line there

**Comment by DeanShin** [comment]
> Can you change line 248 to perhaps a single quoted backtick as well, and potentially not on it's own line? Seems to also not be rendering correctly based on it being on it's own line there

Updated

**Review by onzfonz — APPROVED** [review]
LGTM

**Comment by onzfonz** [comment]
@DeanShin feel free to merge your pull request when you'd like

**Pull request merged**
