### PR TITLE
issue # 12  EclipseLoot.md resolved

### LINKED ISSUE #3: Quick Reference for Understanding and Using Eclipse - Adding eclipse keyboard shortcuts
A cool resource to add to this lab would be adding a table of keyboard shortcuts for eclipse for both Mac and Windows and I would like to make that addition to this document

### PR DESCRIPTION
**Pull request by AlihaNaeem**
pull request for eclipseLoot.md issue fixes #3

### CODE REVIEW

**Review by onzfonz — CHANGES_REQUESTED** [review]
Please fix the linter errors, which can be viewed from github actions.
I will not look at the changes or ask to request until it is green.

Also, if you took these shortcuts from somewhere, then you need to cite the source for this as well, which should be linked to or credit should be given at the bottom of the table

**Comment by onzfonz** [comment]
please also link to the issue as it's described in the assignment

**Review by onzfonz — CHANGES_REQUESTED** [review]
please link to the issue in the description as it states in the assignment.

You need to say "fixes " and then the issue number
you can see it by looking at the other pull requests

**Review by AlihaNaeem — COMMENTED** [review]
fixed issue # 12

**Review by onzfonz — CHANGES_REQUESTED** [review]
you still need to update the description, please see message from discord or edit using the three dots right below the pull request title, or just search "how to edit pull request description"

**Review by onzfonz — APPROVED** [review]
LGTM

**Pull request merged**
