### PR TITLE
Fixes #73

### LINKED ISSUE #73: 67-Sequence.md - Include example and images
Problem Description:
- The Sequence Diagram Mini-Lab provides detailed instructions on creating sequence diagrams using PlantUML. However, it lacks concrete examples to illustrate the concepts effectively. 

Solution:
- I recommend adding examples to the lab instructions such as sample sequence diagrams or code snippets demonstrating the concepts discussed.  I would also add images of what it would look like in PlantUML if we were to put in the example code.

### PR DESCRIPTION
**Pull request by JohnP105**
Problem Description:
- The Sequence Diagram Mini-Lab provides detailed instructions on creating sequence diagrams using PlantUML. However, it lacks concrete examples to illustrate the concepts effectively.

Solution:
- I added examples to the lab instructions such as sample sequence diagrams and code snippets demonstrating the concepts discussed. I also added images of what it would look like in PlantUML if we were to put in the example code.

### CODE REVIEW

**Review by onzfonz — CHANGES_REQUESTED** [review]
Please update the branch. Also move the image into a sequence diagram folder similar to the other labs.
Then re request review (we'll do one more set of changes then)

**Comment by onzfonz** [comment]
Also the fixes should not be in the title but in the description

**Comment by onzfonz** [comment]
Please fix that as well @JohnP105

**Comment by JohnP105** [comment]
I've fixed it.  Please look over it @onzfonz

**Review by onzfonz — COMMENTED** [review]
Sorry looks like two more back and forths still.
Can you write a sentence or two explaining what the diagram is or what it is doing? Like here's a sample that helps you understand blank
Then I'll have one more small modification to make after that change @JohnP105

**Comment by JohnP105** [comment]
Alright, I added the instructions @onzfonz

**Review by onzfonz — CHANGES_REQUESTED** [review]
@JohnP105 this should be the last change as long as this passes the tests.  ***Please use the commit suggestion button in the PR page to commit the change directly from GitHub***

**Review by JohnP105 — COMMENTED** [review]
Approve for commit @onzfonz

**Review by onzfonz — APPROVED** [review]
LGTM

**Pull request merged**
